import sys
import os
sys.path.append(os.path.abspath(".")) 
from dotenv import load_dotenv
load_dotenv()
from app.agents.summarizer import SummarizerAgent

def test_summarizer_agent():
    agent = SummarizerAgent()

    # Fake user query
    query = "I need 10mm steel bolts for over 1,000 units within 9 days."

    # Best offer from Evaluator
    best_offer = (
        "Supplier: QuickFix\n"
        "Unit Price: $0.75/unit\n"
        "Delivery Time: 10 days\n"
        "Payment Terms: Net 45\n"
        "Risk: Low (95% on-time delivery history)"
    )

    # Other offers to compare against
    other_offers = (
        "Supplier: Premier Metals\n"
        "Unit Price: $0.70/unit\n"
        "Delivery: 8 days\n"
        "Risk: High (past quality issues)\n\n"
        "Supplier: BoltMaster\n"
        "Unit Price: $0.82/unit\n"
        "Delivery: 7 days\n"
        "Risk: Medium (limited data)"
    )

    # Call summarizer
    result = agent.summarize(query, best_offer, other_offers)

    print("\n📋 Final Summary Generated by SummarizerAgent:\n")
    print(result)

# Run if standalone
if __name__ == "__main__":
    test_summarizer_agent()
